project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Labs.qmd
        text: Labs
      - href: Project.qmd
        text: Project
      - href: Presentation.qmd
        text: Presentation
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual


