project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

git remote set-url origin https://github.com/cameron0707/Lab-7.git
git add .
git commit -m "first commit"
git branch -M main
git push -u origin main

