---
title: "Motivating Reasons"
---
1. One of the motivations for this research comes from an increasing scientific interest in understanding how microbial communities influence and are influenced by different ecosystems and environmental factors. In this project, Alphaproteobacteria and Chase Lake Wetlands were the main focus of this study. Wetlands serve crucial ecological functions, including water filtration and carbon storage, and microbes are at the heart of these processes which are important in understanding how ecosystems work. Microbial communities, like Alphaproteobacteria, are sensitive to environmental changes and can provide early warning signs of ecosystem stress or degradation. 

2. Another motivation is that studying these microorganisms can help predict the impacts of environmental changes on wetland and other environment's health and informs conservation strategies. The Chase Lake Wetlands serve as an important case study due to their unique ecological characteristics and the pressures they face from agricultural runoff and climate change.
